USE PORTFOLIO;
CREATE TABLE DEALS
(
Ep INT,
Brand VARCHAR(20),
Male INT,
Female INT,
Location VARCHAR(20),
Idea VARCHAR (50),
Sector varchar(50),
Deal VARCHAR(50),
Amount_Invested_Lcs INT,
Amout_Asked_Lcs INT,
Debt_Invested INT,
Debt_Asked INT, 
Equity_Taken FLOAT,
Equity_Asked FLOAT, 
Avg_age VARCHAR(10), 
Team_members INT,
Ashneer_Amount_Invested	INT, 
Ashneer_Equity_Taken FLOAT,
Namita_Amount_Invested INT,
Namita_Equity_Taken FLOAT,
Anupam_Amount_Invested INT, 
Anupam_Equity_Taken FLOAT,
Vineeta_Amount_Invested INT, 
Vineeta_Equity_Taken FLOAT,
Aman_Amount_Invested INT, 
Aman_Equity_Taken	FLOAT,
Peyush_Amount_Invested INT, 
Peyush_Equity_Taken FLOAT,
Ghazal_Amount_Invested INT, 
Ghazal_Equity_Taken FLOAT,
Total_investors INT, 
Partners VARCHAR(20)
)